version: '3.8'

services:
  gnomotron:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
      - "8055:8055"
    environment:
      GNOMOTRON_TELEGRAM_TOKEN: "${GNOMOTRON_TELEGRAM_TOKEN}"
      GNOMOTRON_TELEGRAM_API_KEY: "${GNOMOTRON_TELEGRAM_API_KEY}"
      GNOMOTRON_MONGO_URI: "${GNOMOTRON_MONGO_URI}"
      GNOMOTRON_MONGO_DB: "${GNOMOTRON_MONGO_DB}"
      BOT_NAME: "${BOT_NAME}"
      MAX_DIALOGUE_SIZE: "${MAX_DIALOGUE_SIZE}"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - ./data/mongodb:/data/db

  mongoclient:
    image: mongoclient/mongoclient:latest
    ports:
      - "8081:3000"
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: "${GNOMOTRON_MONGO_URI}"
    depends_on:
      - mongodb
 