apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8055
          env:
            - name: STT_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: STT_URI
            - name: GNOMOTRON_TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: GNOMOTRON_TELEGRAM_TOKEN
            - name: GPT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: GPT_API_KEY
            - name: GNOMOTRON_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: GNOMOTRON_MONGO_URI
            - name: GNOMOTRON_MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: GNOMOTRON_MONGO_DB
            - name: BOT_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: BOT_NAME

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .nodePort }}
    {{- end }}
