apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  GNOMOTRON_TELEGRAM_TOKEN: {{ .Values.secrets.GNOMOTRON_TELEGRAM_TOKEN | quote }}
  GPT_API_KEY: {{ .Values.secrets.GPT_API_KEY | quote }}
  GNOMOTRON_MONGO_URI: {{ .Values.secrets.GNOMOTRON_MONGO_URI | quote }}
  GNOMOTRON_MONGO_DB: {{ .Values.secrets.GNOMOTRON_MONGO_DB | quote }}
  STT_URI: {{ .Values.secrets.STT_URI | quote }}
  BOT_NAME: {{ .Values.secrets.BOT_NAME | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.MONGO_INITDB_ROOT_USERNAME | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.MONGO_INITDB_ROOT_PASSWORD | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.secrets.MONGO_INITDB_DATABASE | quote }}
  STT_MODEL: {{ .Values.secrets.STT_MODEL | quote }}
