name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  build-push:
    name: build docker image
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: docker/login-action@v1
        name: login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push the image
        run: |
          docker image build -t 'ghcr.io/nekoMalchik/gnomotron:$GITHUB_SHA' -t 'ghcr.io/nekoMalchik/gnomotron:latest' .
          docker image push 'ghcr.io/nekoMalchik/gnomotron:$GITHUB_SHA'
          docker image push 'ghcr.io/nekoMalchik/gnomotron:latest'

  deploy:
    name: run the app
    runs-on: self-hosted
    needs: 
      - build-push
    
    steps:
      - uses: actions/checkout@v2.3.4
        with: 
          ref: ci
          submodules: true
      
      - uses: docker/login-action@v1
        name: login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: run app
        run: make pull down up
